sudo: required
language: go
go:
  - "1.10.x"
services:
  - docker

notifications:
  email: false

install: true

before_install:
  - make db_up
  - go get ./...

script:
  - env GO111MODULE=on make build
  - env GO111MODULE=on make test