version: "3.3"
services:
  server1:
    image: percona:5.7
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
    ports:
      - "33060:3306"
  server2:
    image: percona:5.7
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
    ports:
      - "33062:3306"
